name: muscle_zone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-334.3.beta

dependencies:
  flutter:
    sdk: flutter

  # State management, routing and dependency injection
  get: ^4.6.6

  # Utils
  flutter_dotenv: ^5.2.1
  http: ^1.2.2
  shared_preferences: ^2.3.3

  # UI components
  flutter_svg: ^2.0.14
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
