name: muscle_zone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-334.3.beta

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.6

  # Network & API
  http: ^1.2.2
  json_annotation: ^4.9.0

  # Local Storage
  shared_preferences: ^2.3.3
  hive_flutter: ^1.1.0

  # Localization
  easy_localization: ^3.0.5

  # Environment
  flutter_dotenv: ^5.2.1

  # UI Components
  flutter_svg: ^2.0.14
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

  # Linting
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/translations/
    - .env
